apiVersion: v1
kind: Secret
metadata:
  name: ruby-app-secrets
  namespace: hf-review
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXMKCg== # base64 encoded username postgres
  POSTGRES_PASSWORD: MTIzCg== # base64 encoded password 123
  POSTGRES_PORT: NTQzMg== # base64 encoded port
